import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='flex items-center justify-center w-full min-h-screen'>
        <h1 className='font-bold text-3xl'>
          Welcome to <a href='https://nextjs.org'>Next.js!</a>
        </h1>
      </main>
    </>
  )
}

export default Home
